/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Administrator' at '16-12-18 下午3:05' with Gradle 3.2.1
 *
 * @author Administrator, @date 16-12-18 下午3:05
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
